- hosts: all
  become: true
  collections:
    - devsec.hardening
  roles:
    - ssh_hardening

- hosts: all
  become: true
  collections:
    - devsec.hardening
  roles:
    - os_hardening
  vars:
    os_user_pw_ageing: false
    sysctl_overwrite:
      net.ipv4.ip_forward: 1
      net.ipv4.conf.all.forwarding: 1
      net.ipv6.conf.all.forwarding: 0
      net.ipv6.conf.all.disable_ipv6: 0

- hosts: all
  become: true
  roles:
    - wireguard
  vars_prompt:
    - name: duckdns_token
      prompt: What is your DuckDNS token? (blank if DuckDNS is disabled)
      private: true
  vars_files:
    - config.cfg
