---
- name: WireGuard installed
  apt:
    name: wireguard-tools
    state: present
    update_cache: true

- name: WireGuard reload-module-on-update
  file:
    dest: /etc/wireguard/.reload-module-on-update
    state: touch

- name: install wg_admin
  copy:
    src: wg_admin
    dest: /usr/bin/wg_admin
    owner: root
    group: root
    mode: 0755

- name: set wg_admin_deps
  set_fact:
    wg_admin_deps:
      - python3
      - python3-ruamel.yaml

- name: Install wg_admin dependencies
  apt:
    name: "{{ wg_admin_deps|default([]) }}"
    state: present
    update_cache: true

- name: generate WireGuard Private Key
  command: "/usr/bin/wg genkey"
  register: wireguard_private_key_output

- set_fact:
    wireguard_private_key: "{{ wireguard_private_key_output.stdout }}"

- name: wg_admin configured
  template:
    src: wg0.yaml.j2
    dest: "/etc/wireguard/{{ wireguard_interface }}.yaml"
    mode: "0600"

- name: generate WireGuard config
  command: "/usr/bin/wg_admin sync --input /etc/wireguard/{{ wireguard_interface }}.yaml --output /etc/wireguard/{{ wireguard_interface }}.conf"
  become: yes

- name: Set OS specific facts
  set_fact:
    service_name: "wg-quick@{{ wireguard_interface }}"
  tags: always
