---
- name: Include tasks for Armbian
  include_tasks: armbian.yml
  tags: always

- name: WireGuard enabled and started
  service:
    name: "{{ service_name }}"
    state: started
    enabled: true

- meta: flush_handlers
